#!/bin/bash

amass enum --passive -timeout 15 -d $1 -o amass.txt &
subfinder -d $1 -all -o subfinder.txt &
assetfinder $1 -subs-only | grep -v '*' | tee assetfinder.txt &

wait

cat * | sort -u | grep $1 | httpx -o first.txt 
cat first.txt | cut -d "/" -f3 | cut -d " " -f 1 | tee first.txt
cat first.txt | dnsgen - | massdns -r ~/hacking/wordlists/resolvers.txt -t A -o S first.txt -w second.txt -s 1000
cat second.txt | grep -Eo '[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}' | sort -u | tee second.txt
cat first.txt second.txt | sort -u | httpx -no-color -o ../$1.txt -title -status-code -location -content-length &

wait

#rm -rf first.txt second.txt third.txt